### ISSUE TITLE
ffmpeg exited with code 127

### ISSUE THREAD

**Issue by kes-tra** [lyfe00011/whatsapp-bot-md#356]
### I'm having trouble using the most command on Termux. I keep getting an error message from ffmpeg. 

``` 0|kestra | 2024-02-28T03:52:37: [09:22:37.467] ERROR (19838): ffmpeg exited with code 127
0|kestra | 2024-02-28T03:52:37:     err: {
0|kestra | 2024-02-28T03:52:37:       "type": "Error",
0|kestra | 2024-02-28T03:52:37:       "message": "ffmpeg exited with code 127",
0|kestra | 2024-02-28T03:52:37:       "stack":
0|kestra | 2024-02-28T03:52:37:           Error: ffmpeg exited with code 127
0|kestra | 2024-02-28T03:52:37:               at FfmpegCommand.<anonymous> (/root/kestra/lib/fFmpeg.js:1:88490)
0|kestra | 2024-02-28T03:52:37:               at FfmpegCommand.emit (node:events:518:28)
0|kestra | 2024-02-28T03:52:37:               at emitEnd (/root/kestra/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
0|kestra | 2024-02-28T03:52:37:               at /root/kestra/node_modules/fluent-ffmpeg/lib/processor.js:433:16
0|kestra | 2024-02-28T03:52:37:               at wrapper (/root/kestra/node_modules/async/dist/async.js:273:20)
0|kestra | 2024-02-28T03:52:37:               at next (/root/kestra/node_modules/async/dist/async.js:5797:24)
0|kestra | 2024-02-28T03:52:37:               at /root/kestra/node_modules/async/dist/async.js:329:20
0|kestra | 2024-02-28T03:52:37:               at wrapper (/root/kestra/node_modules/async/dist/async.js:273:20)
0|kestra | 2024-02-28T03:52:37:               at next (/root/kestra/node_modules/async/dist/async.js:5797:24)
0|kestra | 2024-02-28T03:52:37:               at /root/kestra/node_modules/async/dist/async.js:329:20 ```


![Screenshot_20240228-051101_WhatsApp](https://github.com/lyfe00011/whatsapp-bot-md/assets/127632758/f33c2d82-24b3-4d9e-be6a-4f5f9b507293)

**Comment by lyfe00011** [comment]
https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/220#issuecomment-450082602

**Comment by lyfe00011** [comment]
try with different Debian image

**Comment by weskerty** [comment]
install ffmpeg
Debian: sudo apt install fmpeg
Windows npm: choco install ffmpeg-full
